export const DsTypes = {
  ancestry: 'sheath.ds.ancestry',
  career: 'sheath.ds.career',
  chapter: 'sheath.ds.chapter',
  class: 'sheath.ds.class',
  commonAbility: 'sheath.ds.commonAbility',
  complication: 'sheath.ds.complication',
  condition: 'sheath.ds.condition',
  cultureBenefit: 'sheath.ds.cultureBenefit',
  dynamicTerrain: 'sheath.ds.dynamicTerrain',
  keywords: 'sheath.ds.keywords',
  kit: 'sheath.ds.kit',
  monster: 'sheath.ds.monster',
  monsterFeature: 'sheath.ds.monsterFeature',
  monsterSection: 'sheath.ds.monsterSection',
  motivationOrPitfall: 'sheath.ds.motivationOrPitfall',
  movement: 'sheath.ds.movement',
  perk: 'sheath.ds.perk',
  retainer: 'sheath.ds.retainer',
  skill: 'sheath.ds.skill',
  title: 'sheath.ds.title',
  treasure: 'sheath.ds.treasure',
};
